pipeline {
    agent {
        docker{
            image "pgupta584/apijavaimage:testng"
            label 'master'
        }
    }
    environment{
        JAVA_HOME = '/usr/lib/jvm/java-17-openjdk-amd64'
        PATH = "${env.JAVA_HOME}/bin:${env.PATH}"
    }

    stages {
        stage('Checkout code from GIT') {
            steps {
                git branch:'master', url:"https://github.com/pgupta584/api_testing_with_java_restassured.git"
            }
        }
        stage('Run The Tests') {
            steps {
                script{
                sh 'mvn clean test'
                }
            }
        }
    }

    post {
        always {
            script {
                sh 'docker system prune -a'
            }
        }
    }
}

